AMV.TourReservation.Web/Controllers/AuthController.cs
using AMV.TourReservation.Domain.Entities;
using AMV.TourReservation.Web.Models;
using AMV.TourReservation.Web.Service;
using AutoMapper;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Net.Http;
using System.Reflection;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;

namespace AMV.TourReservation.Web.Controllers
{
    public class AuthController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;
        private readonly IMapper _mapper;
        private readonly TokenProvider _tokenProvider;

        public AuthController(IHttpClientFactory httpClientFactory, IMapper mapper, TokenProvider tokenProvider)
        {
            this._httpClientFactory = httpClientFactory;
            this._mapper = mapper;
            this._tokenProvider = tokenProvider;
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login([FromBody]UserViewModel userViewModel)
        {
            if (!ModelState.IsValid) 
            {
                return BadRequest(ModelState);
            };
            using (var client = _httpClientFactory.CreateClient("TourReservationAPI")) 
            {
                var json = JsonConvert.SerializeObject(userViewModel);

                var content = new StringContent(json, Encoding.UTF8, "application/json");

                var response = await client.PostAsync("api/auth/login", content);

                if (response.IsSuccessStatusCode)
                {
                    var responseJson = await response.Content.ReadAsStringAsync();
                    var loginResponse = JsonConvert.DeserializeObject<LoginResponseDto>(responseJson);

                    await SignInUser(loginResponse);
                    _tokenProvider.SetToken(loginResponse.Token);
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    return RedirectToAction("Login");
                }
            }
            
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            _tokenProvider.ClearToken();
            return RedirectToAction("Index", "Home");
        }

        private async Task SignInUser(LoginResponseDto responseDto)
        {
            var handler = new JwtSecurityTokenHandler();
            var jwt = handler.ReadJwtToken(responseDto.Token);
            var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);

            identity.AddClaim(new Claim(JwtRegisteredClaimNames.Name,
                jwt.Claims.FirstOrDefault(u => u.Type ==JwtRegisteredClaimNames.Name).Value));

            var principal = new ClaimsPrincipal(identity);
            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);
        }
    }
}

AMV.TourReservation.Web/Controllers/TourController.cs
using AutoMapper;
using AMV.TourReservation.Domain.Entities;
using Microsoft.AspNetCore.Mvc;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using AMV.TourReservation.Web.Models;
using System.Collections.Generic;
using System;
using System.Net;
using Microsoft.AspNetCore.Authorization;
using AMV.TourReservation.Web.Service;

public class TourController : Controller
{
    private readonly HttpClient _httpClient;
    private readonly IMapper _mapper;
    private readonly TokenProvider _tokenProvider;

    public TourController(IHttpClientFactory httpClientFactory, IMapper mapper, TokenProvider tokenProvider)
    {
        _httpClient = httpClientFactory.CreateClient("TourReservationAPI");
        _mapper = mapper;
        this._tokenProvider = tokenProvider;
    }

    [Authorize]
    public async Task<IActionResult> GetTours()
    {
        HttpRequestMessage message = new HttpRequestMessage();
        message.Headers.Add("Accept", "application/json");
        var token = _tokenProvider.GetToken();
        message.Headers.Add("Authorization", "Bearer " + token);
        var uri = _httpClient.BaseAddress.ToString() + "api/tour";
        message.RequestUri = new Uri(uri);
        message.Method = HttpMethod.Get;


        var response = await _httpClient.SendAsync(message);

        if (response.IsSuccessStatusCode)
        {
            var json = await response.Content.ReadAsStringAsync();
            var tours = JsonConvert.DeserializeObject<List<Tour>>(json);
            return View(_mapper.Map<List<TourViewModel>>(tours));
        }
        return View(new List<TourViewModel>());
    }

    [Authorize]
    public async Task<IActionResult> DeleteTour(int id)
    {
        try
        {
            HttpRequestMessage message = new HttpRequestMessage();
            message.Headers.Add("Accept", "application/json");
            var token = _tokenProvider.GetToken();
            message.Headers.Add("Authorization", "Bearer " + token);
            var uri = _httpClient.BaseAddress.ToString() + $"api/tour/{id}";
            message.RequestUri = new Uri(uri);
            message.Method = HttpMethod.Delete;


            var response = await _httpClient.SendAsync(message);

            if (response.IsSuccessStatusCode)
            {
                return NoContent();
            }
            else
            {
                return BadRequest();
            }
        }
        catch (Exception ex)
        {
            return StatusCode(500, $"Internal server error: {ex.Message}");
        }
    }

    [Authorize]
    public async Task<IActionResult> AddTour([FromBody] TourViewModel model)
    {
        if (!ModelState.IsValid)
        {
            return BadRequest(ModelState);
        }

        HttpRequestMessage message = new HttpRequestMessage();
        message.Headers.Add("Accept", "application/json");
        var token = _tokenProvider.GetToken();
        message.Headers.Add("Authorization", "Bearer " + token);
        var uri = _httpClient.BaseAddress.ToString() + "api/tour";
        message.RequestUri = new Uri(uri);
        message.Method = HttpMethod.Post;
        message.Content = new StringContent(JsonConvert.SerializeObject(model), Encoding.UTF8, "application/json");
        var response = await _httpClient.SendAsync(message);

        if (response.IsSuccessStatusCode)
        {
            return Ok();
        }

        return StatusCode((int)response.StatusCode, await response.Content.ReadAsStringAsync());
    }

}

AMV.TourReservation.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AMV.TourReservation.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <div class="alert col-12 alert-success o-alerts" style="display:none;" id="alertok">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    </div>
    <div class="alert col-12 o-alerts alert-danger" style="display:none;" id="alerterror">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    </div>
    <div class="d-flex min-vh-100" id="container">
        <!-- Sidebar content -->
        @await Html.PartialAsync("_SidebarMenu")
        <div class="content h-auto w-100 p-2">
            <!-- Main content -->
            @RenderBody()
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

AMV.TourReservation.Web/Views/Shared/_SidebarMenu.cshtml
<div class="sidebar">
    <h2 class="text-center text-light">AMV Travel</h2>
    @if (!User.Identity.IsAuthenticated)
    {
        <a href="#" id="login" data-url="@Url.Action("Login", "Auth")" class="dashboard-nav-item nav-link"><i class="fas fa-sign-out-alt"></i> Login </a>
    }
    else
    {
        <a href="#" id="tourscardsLink" class="nav-link" data-url="@Url.Action("Index", "Home")">
            <i class="fas fa-home"></i> Inicio
        </a>

        <a href="#" id="toursLink" class="nav-link" data-url="@Url.Action("GetTours", "Tour")">
            <i class="fa-solid fa-earth-americas"></i> Tours
        </a>

        <hr />

        <div class="nav-item-divider"></div>
        <a href="#" id="logout" class=" nav-link" data-url="@Url.Action("Logout", "Auth")"><i class="fas fa-sign-out-alt"></i> Cerrar Sesion </a>

    }
</div>